inherits = "base.toml"

[gdm]

# [pacman]
# keyrings = ['archlinux', 'apricity']

[zsh]
[zsh.zshrc]
apricity = [
    '''source /usr/share/zsh/site-contrib/powerline.zsh''',
    '''zstyle ':completion:*' menu select''',
    # '''case $TERM in''',
    # "    xterm*) ",
    # "    bindkey \"^[[H\" beginning-of-line # Home (xterm)",
    # '''    bindkey '^[[F' end-of-line # End (xterm)''',
    # '''    bindkey '\e[3~' delete-char  # Delete''',
    # '''    bindkey '^[[5~'  history-beginning-search-backward # Page Up''',
    # '''    bindkey '^[[6~'  history-beginning-search-forward # Page Down''',
    # '''    bindkey '^[[2~' overwrite-mode # Insert''',
    # ''';;''',
    # '''esac''',
]

[pacman]
[pacman.packages]
    apricity = [
        "python",
        "xz",
	"random-test"
    ]

[vim]
plugin_manager = "pathogen"
# [vim.plugins]
#     apricity = [
#         "https://github.com/chriskempson/base16-vim.git/",
#         "https://github.com/scrooloose/syntastic.git/",
#         "https://github.com/bling/vim-airline/",
#         "https://github.com/hynek/vim-python-pep8-indent.git/",
#         "https://github.com/mhinz/vim-signify/",
#         "https://github.com/flazz/vim-colorschemes.git",
#         "https://github.com/luochen1990/rainbow.git",
#         "https://github.com/rust-lang/rust.vim.git",
#         "https://github.com/cespare/vim-toml.git",
#     ]
# [vim.vimrc]
#     base = [
#         "syntax on",
#         "set autoread",
#         "set number",
#     ]
#     python = [
#         "set expandtab",
#         "set shiftwidth=4",
#         "set softtabstop=4",
#     ]
#     colorscheme = [
#         "colorscheme kalisi",
#         "set background=dark",
#         "let t_Co = 256",
#     ]
#     airline = [
#         "let g:airline_powerline_fonts = 1",
#         "let g:syntastic_check_on_open = 1",
#         "let g:airline#extensions#tabline#enabled = 1",
#         "let g:airline_theme=\"base16\" ",
#     ]
#     tfbrain = [
#         'map <C-p> :w \| !./push.sh<CR><CR>',
#     ]
#     ycm = [
#         "let g:ycm_collect_identifiers_from_tags_files = 1",
#         "let g:ycm_use_ultisnips_completer = 1",
#         "let g:ycm_seed_identifiers_with_syntax = 1 ",
#         "let g:ycm_complete_in_comments = 1",
#         "let g:ycm_complete_in_strings = 1",
#         "let g:ycm_autoclose_preview_window_after_insertion = 1",
#         "let g:ycm_key_invoke_completion = '<S-Enter>'",
#         "map <C-m> :YcmCompleter GoTo<CR>",
#         "nmap <C-k> :YcmCompleter GetDoc<CR>",
#     ]
#     rainbow = [
#         "let g:rainbow_active = 1"
#     ]

[code]
[code.user]
gen = ['echo "Hello world!"', 'echo "Running user code"']
[code.root]
gen = ['echo "Hello world #2!"', 'echo "Running root code"']
